# workshop-template-b, evanwill
# https://github.com/evanwill/workshop-template-b
# A Jekyll template for a simple workshop website

# Site settings
# title appears in the header
title: Podcast Workshop
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Font Awesome 5 free, https://fontawesome.com/icons?d=gallery&m=free
# some options: fas fa-wrench; fas fa-cogs; fas fa-code; fas fa-chalkboard-teacher; fas fa-book-open
title-icon: fas fa-microphone
# description and keywords for meta tags
description: "Create a workshop website quick and easy!"
keywords: "workshops, websites, gh-pages, jekyll"
featured-image: "/images/uidaho-workshop.jpg"

# author settings for cc-by, appears in the footer
author: Corey Oglesby
pub_year: 2019
github_username: coroglesby

# add the full url for the github repository
repo: "https://github.com/coroglesby/podcast"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://coroglesby.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /podcast

# add search box to footer?
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "default"
# Build settings
markdown: kramdown
